import { createApp } from "vue";
import App from "./App.vue";
import "./index.less";
import "highlight.js/styles/monokai-sublime.css";
import hljs from "highlight.js";
import "viewerjs/dist/viewer.css";
import Viewer from "v-viewer";
import HeightCode from "./components/HeightCode.vue";
import PageTitle from "./components/PageTitle.vue";
import PageContent from "./components/PageContent.vue";
import TagText from "./components/TagText.vue";
import TableVue from "./components/Table.vue";
import PlayText from "./components/PlayText.vue";
import { router } from "./router";
const app = createApp(App);
app.directive("highlight", function (el) {
  const blocks = el.querySelectorAll("pre code");
  blocks.forEach((block: any) => {
    hljs.highlightBlock(block);
  });
});
app.use(router);
app.use(Viewer);
app.mount("#app");
app.component("HeightCode", HeightCode);
app.component("PageTitle", PageTitle);
app.component("PageContent", PageContent);
app.component("TagText", TagText);
app.component("TableVue", TableVue);
app.component("PlayText", PlayText);
